package com.sage.bif.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

    COMMON_INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "SYSTEM_INTERNAL_ERROR", "서버에 알 수 없는 오류가 발생했습니다."),
    COMMON_BAD_REQUEST(HttpStatus.BAD_REQUEST, "COMMON_BAD_REQUEST", "잘못된 요청입니다."),
    COMMON_UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "COMMON_UNAUTHORIZED", "인증이 필요합니다."),
    COMMON_FORBIDDEN(HttpStatus.FORBIDDEN, "COMMON_FORBIDDEN", "접근 권한이 없습니다."),
    COMMON_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON_NOT_FOUND", "요청하신 정보를 찾을 수 없습니다."),
    COMMON_CONFLICT(HttpStatus.CONFLICT, "COMMON_CONFLICT", "충돌이 발생했습니다."),
    COMMON_VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "COMMON_VALIDATION_FAILED", "요청 데이터가 유효하지 않습니다."),
    COMMON_EXTERNAL_API_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_EXTERNAL_API_FAILED", "외부 서비스 연동에 실패했습니다."),

    COMMON_EVENT_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "EVENT_PUBLISH_FAILED", "이벤트 발행에 실패했습니다."),
    COMMON_EVENT_PROCESSING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "EVENT_PROCESSING_FAILED", "이벤트 처리 중 오류가 발생했습니다."),
    COMMON_EVENT_DATA_INVALID(HttpStatus.BAD_REQUEST, "EVENT_DATA_INVALID", "이벤트 데이터 형식이 올바르지 않습니다."),
    COMMON_EVENT_LISTENER_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "EVENT_LISTENER_FAILED", "이벤트 리스너 실행에 실패했습니다."),
    COMMON_EVENT_TIMEOUT(HttpStatus.REQUEST_TIMEOUT, "EVENT_TIMEOUT", "이벤트 처리 시간이 초과되었습니다."),
    COMMON_EVENT_RETRY_EXCEEDED(HttpStatus.INTERNAL_SERVER_ERROR, "EVENT_RETRY_EXCEEDED", "이벤트 재시도 횟수를 초과했습니다."),
    COMMON_EVENT_DUPLICATE(HttpStatus.CONFLICT, "EVENT_DUPLICATE", "중복된 이벤트가 감지되었습니다."),
    COMMON_EVENT_ORDER_VIOLATION(HttpStatus.BAD_REQUEST, "EVENT_ORDER_VIOLATION", "이벤트 처리 순서가 올바르지 않습니다."),
    COMMON_EVENT_DEPENDENCY_MISSING(HttpStatus.PRECONDITION_FAILED, "EVENT_DEPENDENCY_MISSING", "의존하는 이벤트가 누락되었습니다."),

    COMMON_ASYNC_TASK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "ASYNC_TASK_FAILED", "비동기 작업 실행에 실패했습니다."),
    COMMON_ASYNC_QUEUE_FULL(HttpStatus.SERVICE_UNAVAILABLE, "ASYNC_QUEUE_FULL", "비동기 작업 큐가 가득 찼습니다."),
    COMMON_ASYNC_THREAD_POOL_EXHAUSTED(HttpStatus.SERVICE_UNAVAILABLE, "ASYNC_THREAD_POOL_EXHAUSTED", "비동기 스레드풀이 고갈되었습니다."),

    COMMON_SCHEDULE_TASK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SCHEDULE_TASK_FAILED", "스케줄 작업 실행에 실패했습니다."),
    COMMON_SCHEDULE_CONFLICT(HttpStatus.CONFLICT, "SCHEDULE_CONFLICT", "스케줄 작업이 충돌했습니다."),
    COMMON_SCHEDULE_CONFIG_INVALID(HttpStatus.BAD_REQUEST, "SCHEDULE_CONFIG_INVALID", "스케줄 설정이 올바르지 않습니다."),

    COMMON_NOTIFICATION_SEND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "NOTIFICATION_SEND_FAILED", "알림 발송에 실패했습니다."),
    COMMON_NOTIFICATION_TEMPLATE_INVALID(HttpStatus.BAD_REQUEST, "NOTIFICATION_TEMPLATE_INVALID", "알림 템플릿이 올바르지 않습니다."),
    COMMON_NOTIFICATION_RECIPIENT_INVALID(HttpStatus.BAD_REQUEST, "NOTIFICATION_RECIPIENT_INVALID", "알림 수신자 정보가 올바르지 않습니다."),

    COMMON_DATA_SYNC_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "DATA_SYNC_FAILED", "데이터 동기화에 실패했습니다."),
    COMMON_DATA_INCONSISTENCY(HttpStatus.CONFLICT, "DATA_INCONSISTENCY", "데이터 불일치가 감지되었습니다."),
    COMMON_DATA_VERSION_CONFLICT(HttpStatus.CONFLICT, "DATA_VERSION_CONFLICT", "데이터 버전 충돌이 발생했습니다."),

    COMMON_AI_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "AI_SERVICE_UNAVAILABLE", "AI 서비스를 사용할 수 없습니다."),
    COMMON_AI_REQUEST_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "AI_REQUEST_FAILED", "AI 서비스 요청에 실패했습니다."),
    COMMON_AI_RESPONSE_INVALID(HttpStatus.BAD_GATEWAY, "AI_RESPONSE_INVALID", "AI 서비스 응답이 올바르지 않습니다."),
    COMMON_AI_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "AI_QUOTA_EXCEEDED", "AI 서비스 사용량이 초과되었습니다."),
    COMMON_AI_MODEL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "AI_MODEL_ERROR", "AI 모델 처리 중 오류가 발생했습니다."),
    COMMON_AI_CONTENT_FILTERED(HttpStatus.BAD_REQUEST, "AI_CONTENT_FILTERED", "AI 서비스에서 부적절한 콘텐츠로 판단되었습니다."),
    COMMON_AI_CONTENT_VIOLATION(HttpStatus.BAD_REQUEST, "AI_CONTENT_VIOLATION", "부적절한 콘텐츠가 감지되었습니다."),
    COMMON_AI_TIMEOUT(HttpStatus.REQUEST_TIMEOUT, "AI_TIMEOUT", "AI 서비스 응답 시간이 초과되었습니다."),

    COMMON_CACHE_ACCESS_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "CACHE_ACCESS_FAILED", "캐시 접근에 실패했습니다."),
    COMMON_CACHE_EXPIRED(HttpStatus.NOT_FOUND, "CACHE_EXPIRED", "캐시 데이터가 만료되었습니다."),
    COMMON_PERFORMANCE_DEGRADED(HttpStatus.SERVICE_UNAVAILABLE, "PERFORMANCE_DEGRADED", "시스템 성능이 저하되어 일시적으로 서비스를 제한합니다."),

    AUTH_FAILED(HttpStatus.UNAUTHORIZED, "AUTH_FAILED", "인증에 실패했습니다. 자격 증명을 확인해주세요."),
    AUTH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "AUTH_TOKEN_INVALID", "유효하지 않거나 만료된 토큰입니다."),
    AUTH_ACCOUNT_NOT_FOUND(HttpStatus.UNAUTHORIZED, "AUTH_ACCOUNT_NOT_FOUND", "해당 계정을 찾을 수 없습니다."),
    AUTH_ALREADY_REGISTERED(HttpStatus.CONFLICT, "AUTH_ALREADY_REGISTERED", "이미 등록된 계정입니다."),
    AUTH_INVALID_INVITATION_CODE(HttpStatus.BAD_REQUEST, "AUTH_INVALID_INVITATION_CODE", "초대 코드가 올바르지 않습니다."),
    AUTH_PASSWORD_MISMATCH(HttpStatus.UNAUTHORIZED, "AUTH_PASSWORD_MISMATCH", "비밀번호가 일치하지 않습니다."),
    AUTH_NICKNAME_DUPLICATE(HttpStatus.CONFLICT, "AUTH_NICKNAME_DUPLICATE", "이미 사용 중인 닉네임입니다."),
    AUTH_NICKNAME_INVALID(HttpStatus.BAD_REQUEST, "AUTH_NICKNAME_INVALID", "닉네임 형식이 올바르지 않습니다."),
    AUTH_ADMIN_REQUIRED(HttpStatus.FORBIDDEN, "AUTH_ADMIN_REQUIRED", "관리자 계정만 접근할 수 있습니다."),
    AUTH_NOT_BIF_ACCOUNT(HttpStatus.FORBIDDEN, "AUTH_NOT_BIF_ACCOUNT", "BIF 계정만 접근할 수 있습니다."),
    AUTH_NOT_GUARDIAN_ACCOUNT(HttpStatus.FORBIDDEN, "AUTH_NOT_GUARDIAN_ACCOUNT", "보호자 계정만 접근할 수 있습니다."),


    PROFILE_BIF_NOT_CONNECTED(HttpStatus.NOT_FOUND, "PROFILE_BIF_NOT_CONNECTED", "연결된 BIF 계정이 없습니다."),
    PROFILE_STAT_DATA_NOT_FOUND(HttpStatus.NOT_FOUND, "PROFILE_STAT_DATA_NOT_FOUND", "해당 기간의 통계 데이터를 찾을 수 없습니다."),
    PROFILE_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "PROFILE_DATE_RANGE_INVALID", "날짜 범위가 올바르지 않습니다."),

    TODO_NOT_FOUND(HttpStatus.NOT_FOUND, "TODO_NOT_FOUND", "해당 할 일을 찾을 수 없습니다."),
    TODO_INVALID_INPUT(HttpStatus.BAD_REQUEST, "TODO_INVALID_INPUT", "할 일 입력이 올바르지 않습니다."),
    TODO_AI_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "TODO_AI_GENERATION_FAILED", "할 일 자동 생성에 실패했습니다."),
    TODO_ALREADY_COMPLETED(HttpStatus.BAD_REQUEST, "TODO_ALREADY_COMPLETED", "이미 완료된 할 일입니다."),
    TODO_ROUTINE_INVALID_COMPLETION(HttpStatus.BAD_REQUEST, "TODO_ROUTINE_INVALID_COMPLETION", "루틴 완료 기록이 유효하지 않습니다."),
    TODO_EVENT_PROCESSING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "TODO_EVENT_PROCESSING_FAILED", "할 일 이벤트 처리에 실패했습니다."),
    TODO_NOTIFICATION_SCHEDULE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "TODO_NOTIFICATION_SCHEDULE_FAILED", "할 일 알림 스케줄링에 실패했습니다."),
    TODO_STATS_UPDATE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "TODO_STATS_UPDATE_FAILED", "할 일 통계 업데이트에 실패했습니다."),
    TODO_ACCESS_DENIED(HttpStatus.FORBIDDEN, "TODO_ACCESS_DENIED", "해당 할일에 접근할 권한이 없습니다."),
    SUBTODO_NOT_FOUND(HttpStatus.NOT_FOUND, "SUBTODO_NOT_FOUND", "해당 세부 할일을 찾을 수 없습니다."),
    SUBTODO_ACCESS_DENIED(HttpStatus.FORBIDDEN, "SUBTODO_ACCESS_DENIED", "해당 세부 할일에 접근할 권한이 없습니다."),
    SUBTODO_INVALID_RELATION(HttpStatus.BAD_REQUEST, "SUBTODO_INVALID_RELATION", "세부 할일이 해당 할일에 속하지 않습니다."),
    SUBTODOS_NOT_COMPLETED(HttpStatus.BAD_REQUEST, "SUBTODOS_NOT_COMPLETED", "모든 세부 할일을 완료해야 합니다."),
    SUBTODO_COUNT_INSUFFICIENT(HttpStatus.BAD_REQUEST, "SUBTODO_COUNT_INSUFFICIENT", "세부 할일은 2개 이상이어야 합니다."),

    DIARY_NOT_FOUND(HttpStatus.FORBIDDEN, "DIARY_NOT_FOUND", "해당 일기를 찾을 수 없습니다."),
    DIARY_INVALID_INPUT(HttpStatus.BAD_REQUEST, "DIARY_INVALID_INPUT", "일기 입력이 올바르지 않습니다."),
    DIARY_ALREADY_EXISTS(HttpStatus.CONFLICT, "DIARY_ALREADY_EXISTS", "해당 날짜에 이미 일기가 존재합니다."),
    DIARY_AI_FEEDBACK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "DIARY_AI_FEEDBACK_FAILED", "일기 피드백 생성에 실패했습니다."),
    DIARY_STAT_DATE_INVALID(HttpStatus.BAD_REQUEST, "DIARY_STAT_DATE_INVALID", "통계 조회 날짜 형식이 올바르지 않습니다."),
    DIARY_NO_DATA_FOR_STAT(HttpStatus.NOT_FOUND, "DIARY_NO_DATA_FOR_STAT", "해당 기간의 일기 데이터가 없습니다."),
    DIARY_EVENT_PROCESSING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "DIARY_EVENT_PROCESSING_FAILED", "일기 이벤트 처리에 실패했습니다."),
    DIARY_EMOTION_ANALYSIS_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "DIARY_EMOTION_ANALYSIS_FAILED", "감정 분석 처리에 실패했습니다."),
    DIARY_FEEDBACK_REGENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "DIARY_FEEDBACK_REGENERATION_FAILED", "일기 피드백 재생성에 실패했습니다."),

    SIM_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "SIM_SESSION_NOT_FOUND", "시뮬레이션 세션을 찾을 수 없습니다."),
    SIM_STEP_NOT_FOUND(HttpStatus.NOT_FOUND, "SIM_STEP_NOT_FOUND", "시뮬레이션 단계를 찾을 수 없습니다."),
    SIM_INVALID_CHOICE(HttpStatus.BAD_REQUEST, "SIM_INVALID_CHOICE", "유효하지 않은 선택입니다."),
    SIM_ALREADY_ENDED(HttpStatus.BAD_REQUEST, "SIM_ALREADY_ENDED", "이미 종료된 시뮬레이션입니다."),
    SIM_INTERNAL_PROCESSING_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_INTERNAL_PROCESSING_ERROR", "시뮬레이션 처리 중 오류가 발생했습니다."),
    SIM_VOICE_SYNTH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_VOICE_SYNTH_FAILED", "음성 생성에 실패했습니다."),
    SIM_EVENT_PROCESSING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_EVENT_PROCESSING_FAILED", "시뮬레이션 이벤트 처리에 실패했습니다."),
    SIM_AI_RESPONSE_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_AI_RESPONSE_GENERATION_FAILED", "시뮬레이션 AI 응답 생성에 실패했습니다."),
    SIM_PROGRESS_TRACKING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_PROGRESS_TRACKING_FAILED", "시뮬레이션 진행 상황 추적에 실패했습니다."),
    SIM_FEEDBACK_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_FEEDBACK_GENERATION_FAILED", "시뮬레이션 피드백 생성에 실패했습니다."),
    SIM_NOT_FOUND(HttpStatus.NOT_FOUND, "SIM_NOT_FOUND", "시뮬레이션을 찾을 수 없습니다."),
    SIM_SESSION_CREATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_SESSION_CREATION_FAILED", "시뮬레이션 세션 생성에 실패했습니다."),
    SIM_NOT_COMPLETED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_NOT_COMPLETED", "시뮬레이션이 아직 완료되지 않았습니다."),
    SIM_TTS_API_CALL_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_TTS_API_CALL_FAILED", "Google TTS API 호출에 실패했습니다."),
    SIM_TTS_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "SIM_TTS_INVALID_REQUEST", "TTS 요청 데이터가 유효하지 않습니다."),
    SIM_TTS_AUDIO_CONVERSION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "SIM_TTS_AUDIO_CONVERSION_FAILED", "음성 변환에 실패했습니다."),
    SIM_TTS_INVALID_VOICE(HttpStatus.BAD_REQUEST, "SIM_TTS_INVALID_VOICE", "지원하지 않는 음성입니다."),
    SIM_TTS_TEXT_TOO_LONG(HttpStatus.BAD_REQUEST, "SIM_TTS_TEXT_TOO_LONG", "변환할 텍스트가 너무 깁니다."),

    STATS_CALCULATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "STATS_CALCULATION_FAILED", "통계 계산에 실패했습니다."),
    STATS_EVENT_PROCESSING_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "STATS_EVENT_PROCESSING_FAILED", "통계 이벤트 처리에 실패했습니다."),
    STATS_MONTHLY_ANALYSIS_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "STATS_MONTHLY_ANALYSIS_FAILED", "월간 통계 분석에 실패했습니다."),
    STATS_EMOTION_AGGREGATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "STATS_EMOTION_AGGREGATION_FAILED", "감정 데이터 집계에 실패했습니다."),
    STATS_REPORT_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "STATS_REPORT_GENERATION_FAILED", "통계 리포트 생성에 실패했습니다."),
    STATS_DATA_INCONSISTENCY(HttpStatus.CONFLICT, "STATS_DATA_INCONSISTENCY", "통계 데이터에 불일치가 발견되었습니다."),

    INVALID_INPUT(HttpStatus.BAD_REQUEST, "INVALID_INPUT", "잘못된 입력입니다."),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND", "사용자를 찾을 수 없습니다."),
    USER_ALREADY_EXISTS(HttpStatus.CONFLICT, "USER_ALREADY_EXISTS", "이미 존재하는 사용자입니다."),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN", "접근 권한이 없습니다."),
    SIMULATION_NOT_FOUND(HttpStatus.NOT_FOUND, "SIMULATION_NOT_FOUND", "시뮬레이션을 찾을 수 없습니다."),
    STATS_NOT_FOUND(HttpStatus.NOT_FOUND, "STATS_NOT_FOUND", "통계를 찾을 수 없습니다."),
    COMMON_UTILITY_CLASS_INSTANTIATION(HttpStatus.INTERNAL_SERVER_ERROR, "UTILITY_CLASS_INSTANTIATION", "유틸리티 클래스는 인스턴스화할 수 없습니다.");

    private final HttpStatus httpStatus;
    private final String code;
    private final String message;

    ErrorCode(HttpStatus httpStatus, String code, String message) {
        this.httpStatus = httpStatus;
        this.code = code;
        this.message = message;
    }

}
