version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: bif
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bif-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bif-network
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:

networks:
  bif-network:
    driver: bridge
