spring:
  application:
    name: bif-dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
  sql:
    init:
      mode: always
      continue-on-error: true
  
  # H2 데이터베이스 설정 (개발용)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # Azure Mysql Flexible Database(배포용) 추가 필요
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  ai:
    azure:
      openai:
        endpoint: ${AZURE_OPENAI_ENDPOINT:https://your-resource.openai.azure.com}
        api-key: ${AZURE_OPENAI_API_KEY:your-api-key}
        resource-name: ${AZURE_OPENAI_RESOURCE_NAME:your-resource}
        deployment:
          name: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-35-turbo}

  # Security 설정
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin123}
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-authentication-method: client_secret_post
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
        shutdown-timeout: 100ms

  # 서버 설정
  server:
    port: 8080
    servlet:
      context-path: /api

  # 로깅 설정 (개발용 상세 로깅)
  logging:
    level:
      root: INFO
      com.sage.bif: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.security: DEBUG
      org.springframework.data.redis: DEBUG
      io.lettuce.core: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # 파일 로깅 설정 (일별 롤링)
    file:
      name: logs/bif-dev.log
    # 로그백 설정 (롤링 파일)
    logback:
      rollingpolicy:
        max-file-size: 10MB
        max-history: 30
        total-size-cap: 1GB
        file-name-pattern: logs/bif-dev-%d{yyyy-MM-dd}.%i.log

  # 개발 도구
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
    info:
      title: "BIF API Documentation (DEV)"
      description: "BIF (Business Intelligence Framework) REST API Documentation - Development Environment"
      version: "1.0.0"
      contact:
        name: "BIF Development Team"
        email: "dev@bif.com"
        url: "https://bif.com"
      license:
        name: "MIT License"
        url: "https://opensource.org/licenses/MIT"
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: true
  packages-to-scan: com.sage.bif
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 애플리케이션 커스텀 설정
app:
  name: "BIF Development"
  version: "1.0.0"
  environment: "development"
  debug: true

  # JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-enough-for-hs256}
  access-expiration: 3600000  # 1시간 (밀리초)
  refresh-expiration: 2592000000  # 30일 (밀리초)