---
name: "✅ Task"
description: "Epic을 구성하는 개별 작업 단위입니다."
title: "✅ [Task] "
labels: task
body:
  - type: textarea
    id: parent-epic
    attributes:
      label: "🚀 상위 Epic (Parent Epic)"
      description: "이 Task가 속한 Epic 이슈 번호를 링크해주세요. (필수)"
      placeholder: "예시) #1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 작업 설명 (Task Description)"
      description: "수행할 작업에 대한 명확한 설명을 작성해주세요."
      placeholder: "예시) 카카오 소셜 로그인 기능을 위한 API를 연동합니다."
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "🎯 작업 목적 (Task Purpose)"
      description: "왜 이 작업이 필요한지 설명해주세요."
      placeholder: "예시) 사용자가 카카오 계정으로 간편하게 로그인할 수 있도록 하기 위함."
    validations:
      required: true

  - type: textarea
    id: todo-list
    attributes:
      label: "📋 상세 작업 내용 (To-Do List)"
      description: "이 작업을 완료하기 위해 필요한 세부 작업들을 체크리스트로 작성해주세요."
      value: |
        - [ ] 세부 작업 1
        - [ ] 세부 작업 2
        - [ ] 세부 작업 3
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: "🏁 완료 기준 (Definition of Done)"
      description: "이 작업이 완료되었다고 판단할 수 있는 기준을 작성해주세요."
      placeholder: |
        - [ ] 카카오 로그인 버튼 클릭 시 인증이 정상적으로 완료된다.
        - [ ] 로그인 성공 후 서버로부터 JWT 토큰을 받아 저장한다.
        - [ ] 관련 기능에 대한 단위 테스트 코드가 작성되었다.
    validations:
      required: true

  - type: textarea
    id: estimated-time
    attributes:
      label: "⏱️ 예상 소요 시간 (Estimated Time)"
      description: "대략적인 작업 시간을 적어주세요."
      placeholder: "예시) 4시간"
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 의존성 (Dependencies)"
      description: "이 작업을 시작하기 전에 완료되어야 할 다른 작업이 있다면 이슈 번호를 링크해주세요. (선택사항)"
      placeholder: "예시) #2"
    validations:
      required: false
---
